### ISSUE TITLE
[bug]Resize window, the UI cannot be adaptive

### ISSUE THREAD

**Issue by litang1006** [syslink/quarkchain-auction#10]
![Screen Shot 2020-04-21 at 3 54 05 PM](https://user-images.githubusercontent.com/44258843/79840541-9d201c00-83e8-11ea-86f2-b11faaa872c9.png)

**Comment by syslink** [comment]
priority: 2

**Comment by syslink** [comment]
fixed

**Comment by litang1006** [comment]
test on http://quarkauction.xchainunion.com/. fixed
