### ISSUE TITLE
[UI Issues]according to UI designer's feedback, please update the webpage.

### ISSUE THREAD

**Issue by litang1006** [syslink/quarkchain-auction#12]
please refer the attachments

[images.zip](https://github.com/syslink/quarkchain-auction/files/4526175/images.zip)
[UI issues.key.zip](https://github.com/syslink/quarkchain-auction/files/4526176/UI.issues.key.zip)

**Comment by ninjaahhh** [comment]
priority 4

**Comment by syslink** [comment]
The pictures in images.zip have been updated.
And what's mean of 'UI issues.key.zip'? I can't open the file 'UI issues.key'.

**Comment by litang1006** [comment]
[UI issues.pdf](https://github.com/syslink/quarkchain-auction/files/4534592/UI.issues.pdf)
I convert it to PDF file, please try again.

**Comment by litang1006** [comment]
there are detailed issues to track, close this issue.
