### ISSUE TITLE
[improvement] Improve explanation during exchange rate proposing 

### ISSUE THREAD

**Issue by ninjaahhh** [syslink/quarkchain-auction#14]
as [people mentioned](https://community.quarkchain.io/t/call-for-help-come-and-test-our-multinative-token-auction/218/2), it's hard to tell the rate is NativeToken/QKC or QKC/NativeToken when setting the rate. how about changing `Exchange Rate` to `NativeToken/QKC`

![image](https://user-images.githubusercontent.com/38544039/80265852-ddcc9f00-864d-11ea-8fab-169cc4e9bdd2.png)

**Comment by ninjaahhh** [comment]
priority 3

**Comment by syslink** [comment]
fixed

**Comment by ninjaahhh** [comment]
now: "NativeToken/QKC"
we want: "NativeToken/QKC:"

**Comment by ninjaahhh** [comment]
also, how about adding a place holder in the input box: `(use decimal numbers such as 0.5, 2, etc.)`

**Comment by litang1006** [comment]
I have a question, I set rate to 5.5 and send a transaction by using native token. then the balance of native token increase 0.0003, the balance of QKC reduce 0.00165, it seems QKC/NativeToken=5.5 not NativeToken/QKC=5.5

![Screen Shot 2020-04-28 at 2 07 48 PM](https://user-images.githubusercontent.com/44258843/80453681-56d43b00-895b-11ea-89ba-c07941b07315.png)

**Comment by syslink** [comment]
fixed
