### ISSUE TITLE
[improvement] Show disabling reason when auction ends

### ISSUE THREAD

**Issue by ninjaahhh** [syslink/quarkchain-auction#15]
we can add help texts on the disabled inputs

![image](https://user-images.githubusercontent.com/38544039/80265887-05bc0280-864e-11ea-82a9-66235c0d8620.png)

**Comment by ninjaahhh** [comment]
use tooltip to say "please end the current auction to start a new round"

**Comment by ninjaahhh** [comment]
priority 3

**Comment by syslink** [comment]
fixed

**Comment by ninjaahhh** [comment]
no it doesn't show up when I tried...

**Comment by litang1006** [comment]
tested it now the message will pop up as below. fixed can be closed.
for start page, the message is "Please start a new round"
for end page, the message is "Please end the current auction to start a new round"
