### ISSUE TITLE
Auto select valid shard to set rate

### ISSUE THREAD

**Issue by syslink** [syslink/quarkchain-auction#16]
When current shard has no enough QKC to set rate, please automatically select a valid shard which has enough QKC to set the rate, following the below steps:
1. let's say a user wants to set rate in shard 7
2. first check user's balance in shard 7, if enough, sign and send the tx
3. else: use a shard in which the user has the most QKC balance, sign and send the cross-shard tx

**Comment by syslink** [comment]
fixed

**Comment by syslink** [comment]
The same workflow of depositing gas reserve has been added.

**Comment by litang1006** [comment]
verified and fixed. please close.
