### ISSUE TITLE
[bug] The rest QKC in auction system smart contract cannot be withdraw.

### ISSUE THREAD

**Issue by litang1006** [syslink/quarkchain-auction#18]
1. In auction system smart contract, there are 109 QKC.
2. During biding, the highest bid is 3.3 QKC
3. The rest QKC displays is 0. (should be 105.7 QKC, and can be withdraw)
![Screen Shot 2020-04-26 at 1 53 10 PM](https://user-images.githubusercontent.com/44258843/80299369-5fdfd380-87c6-11ea-8aeb-e35d02dfdc92.png)
![Screen Shot 2020-04-26 at 1 54 48 PM](https://user-images.githubusercontent.com/44258843/80299370-60786a00-87c6-11ea-97f6-ca86126cc643.png)

**Comment by syslink** [comment]
In the contract code, there is a requirement that the highest bidder can't withdraw.  So 0 QKC is displayed on the UI.

**Comment by litang1006** [comment]
ok, closed it as design.
