### ISSUE TITLE
[bug] the interface will be confused if zoom in/out the screen. 

### ISSUE THREAD

**Issue by litang1006** [syslink/quarkchain-auction#19]
![截屏2020-04-29上午10 26 40](https://user-images.githubusercontent.com/44258843/80555916-622f7100-8a04-11ea-8cd8-0592a0e414e7.png)

**Comment by litang1006** [comment]
![截屏2020-04-29上午10 32 42](https://user-images.githubusercontent.com/44258843/80556081-fb5e8780-8a04-11ea-9950-3b68b7a7f6d3.png)
![截屏2020-04-29上午10 33 12](https://user-images.githubusercontent.com/44258843/80556083-fbf71e00-8a04-11ea-90f5-7c0856b09e90.png)
![截屏2020-04-29上午10 34 06](https://user-images.githubusercontent.com/44258843/80556084-fdc0e180-8a04-11ea-80e2-5c647bffbf1e.png)

**Comment by ninjaahhh** [comment]
priority 3

**Comment by syslink** [comment]
fixed

**Comment by litang1006** [comment]
fixed and closed
