### ISSUE TITLE
[bug] Non-provider can't withdraw QKC reserve

### ISSUE THREAD

**Issue by ninjaahhh** [syslink/quarkchain-auction#5]
![image](https://user-images.githubusercontent.com/38544039/79836110-96e85c00-8364-11ea-99a9-e2f27e13308f.png)

0x6799 has QKC as gas reserve but she's not the liquidity provider. she  should be able to withdraw but there is no withdraw button

**Comment by syslink** [comment]
priority: 5

**Comment by syslink** [comment]
fixed. 
Now, the deposit button is only shown when the user is provider, and the withdraw button is only shown when the user is not provider.

**Comment by litang1006** [comment]
verified and fixed.
