### ISSUE TITLE
[BUG] Cannot register on shard 1～7

### ISSUE THREAD

**Issue by litang1006** [syslink/quarkchain-auction#6]
After mint token, cannot register on share 1~7, an error displays "fail to send transaction"

**Comment by syslink** [comment]
priority: 4

**Comment by syslink** [comment]
Can register, and now user should flush it manually after tx executed successfully, I will check the problem of the auto flush.

**Comment by ninjaahhh** [comment]
@litang1006 can you verify?

**Comment by litang1006** [comment]
can register now, but cannot set rate if there is no QKC on other shard. when set rate, user need deposit QKC on this shard. Is it a bug or design?

**Comment by litang1006** [comment]
can register now, but cannot set rate if there is no QKC on other shard. when set rate, user need deposit QKC on this shard. Is it a bug or design?

**Comment by ninjaahhh** [comment]
> can register now, but cannot set rate if there is no QKC on other shard. when set rate, user need deposit QKC on this shard. Is it a bug or design?

it's the same problem as register, but the solution can be different. I would propose the following workflow:

1. let's say a user wants to set rate in shard 7
1. first check user's balance in shard 7, if enough, sign and send the tx
1. else: use a shard in which the user has the most QKC balance, sign and send the cross-shard tx

**Comment by litang1006** [comment]
I think this workflow is make sence. please confirm with junjia again.

**Comment by ninjaahhh** [comment]
priority 4

**Comment by ninjaahhh** [comment]
should already be fixed. can close

**Comment by litang1006** [comment]
verified it on http://165.227.17.201:9000, now can register and set rate when the current shard haven't enough QKC for gas. Closed it as fixed.
