### ISSUE TITLE
[bug]when balance is 0, withdraw button should be disabled.

### ISSUE THREAD

**Issue by litang1006** [syslink/quarkchain-auction#7]
![Screen Shot 2020-04-21 at 3 47 00 PM](https://user-images.githubusercontent.com/44258843/79839761-9644d980-83e7-11ea-908e-599613058bff.png)

**Comment by syslink** [comment]
priority: 3

**Comment by syslink** [comment]
fixed, please check it.

**Comment by litang1006** [comment]
verified and fixed. close this issue.
